In [43]:
import pandas as pd
import numpy as np

In [5]:
sample = pd.read_csv(r"raw-asset-data.csv")

In [12]:
sample.head()

,Company,Asset Name,Asset Tag,Model,Model No.,Category,Manufacturer,Serial,Purchased,Cost,...,SPL,Impedance,Termination,Webcam,Interface,NFC,Compatibility,Material,Head Type,Size
0,CapeStart Software Private Limited,CS-LP-304,CS-LP-304,Dell Latitude 3000 Series,3490,Laptop,Dell,3BWFBV2,3/20/2019 0:00,"74,222.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CapeStart Software Private Limited,CS-LP-305,CS-LP-305,Dell Latitude 3000 Series,3490,Laptop,Dell,B00HBV2,3/20/2019 0:00,"74,222.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CapeStart Software Private Limited,CS-LP-306,CS-LP-306,Dell Latitude 3000 Series,3490,Laptop,Dell,210HBV2,3/20/2019 0:00,"74,222.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CapeStart Software Private Limited,CS-LP-307,CS-LP-307,Dell Latitude 3000 Series,3490,Laptop,Dell,GYZGBV2,3/20/2019 0:00,"74,222.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CapeStart Software Private Limited,CS-LP-308,CS-LP-308,Dell Latitude 3000 Series,3490,Laptop,Dell,9BWFBV2,3/20/2019 0:00,"74,222.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
sample.columns

Index(['Company', 'Asset Name', 'Asset Tag', 'Model', 'Model No.', 'Category',
       'Manufacturer', 'Serial', 'Purchased', 'Cost', 'EOL', 'Order Number',
       'Supplier', 'Location', 'Address', 'Address.1', 'City', 'State',
       'Country', 'Zip', 'Default Location', 'Address.2', 'Address.3',
       'City.1', 'State.1', 'Country.1', 'Zip.1', 'Checked Out', 'Type',
       'Username', 'Employee No.', 'Manager', 'Department', 'Status',
       'Warranty', 'Warranty Expires', 'Value', 'Diff', 'Fully Depreciated',
       'Checkout Date', 'Expected Checkin Date', 'Created at', 'Updated at',
       'Last Audit', 'Next Audit Date', 'Notes', 'Memory Size', 'Display Size',
       'Resolution', 'Panel Type', 'CPU', 'Generation', 'Core Count',
       'Memory Type', 'Storage', 'Storage Type', 'Operating System',
       'Endpoint Status', 'Domain Status', 'Storage Size', 'SoC',
       'Contrast Ratio', 'Color Depth', 'Colors', 'Brightness',
       'USB Passthrough', 'HDMI', 'DisplayPort', 'VGA', 'DVI', 'VESA Mount',
       'Thunderbolt', 'USB-C', 'GPU', 'Type.1', 'Microphone', 'Secondary HDD',
       'MAC Address', 'Fingerprint Capacity', 'ID Card Capacity',
       'Log Capacity', 'Wireless Display', 'AirPlay 2', 'Google Assistant',
       'HDR', 'Air Remote', 'Form Factor', 'VRAM', 'Fingerprint Sensor',
       'Frequency Response', 'SPL', 'Impedance', 'Termination', 'Webcam',
       'Interface', 'NFC', 'Compatibility', 'Material', 'Head Type', 'Size'],
      dtype='object')

In [26]:
pd.pivot_table?

Signature:
pd.pivot_table(
    data: 'DataFrame',
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins: 'bool' = False,
    dropna: 'bool' = True,
    margins_name: 'str' = 'All',
    observed: 'bool' = False,
    sort: 'bool' = True,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
data : DataFrame
values : column to aggregate, optional
index : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The
    list can contain any of the other types (except list).
    Keys to group by on the pivot table index.  If an array is passed,
    it is being used as the same manner as column values.
columns : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The
    list can contain any of the other types (except list).
    Keys to group by on the pivot table column.  If an array is passed,
    it is being used as the same manner as column values.
aggfunc : function, list of functions, dict, default numpy.mean
    If list of functions passed, the resulting pivot table will have
    hierarchical columns whose top level are the function names
    (inferred from the function objects themselves)
    If dict is passed, the key is column to aggregate and value
    is function or list of functions.
fill_value : scalar, default None
    Value to replace missing values with (in the resulting pivot table,
    after aggregation).
margins : bool, default False
    Add all row / columns (e.g. for subtotal / grand totals).
dropna : bool, default True
    Do not include columns whose entries are all NaN. If True,
    rows with a NaN value in any column will be omitted before
    computing margins.
margins_name : str, default 'All'
    Name of the row / column that will contain the totals
    when margins is True.
observed : bool, default False
    This only applies if any of the groupers are Categoricals.
    If True: only show observed values for categorical groupers.
    If False: show all values for categorical groupers.

    .. versionchanged:: 0.25.0

sort : bool, default True
    Specifies if the result should be sorted.

    .. versionadded:: 1.3.0

Returns
-------
DataFrame
    An Excel style pivot table.

See Also
--------
DataFrame.pivot : Pivot without aggregation that can handle
    non-numeric data.
DataFrame.melt: Unpivot a DataFrame from wide to long format,
    optionally leaving identifiers set.
wide_to_long : Wide panel to long format. Less flexible but more
    user-friendly than melt.

Notes
-----
Reference :ref:`the user guide <reshaping.pivot>` for more examples.

Examples
--------
>>> df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
...                          "bar", "bar", "bar", "bar"],
...                    "B": ["one", "one", "one", "two", "two",
...                          "one", "one", "two", "two"],
...                    "C": ["small", "large", "large", "small",
...                          "small", "large", "small", "small",
...                          "large"],
...                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
...                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})
>>> df
     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

This first example aggregates values by taking the sum.

>>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
...                     columns=['C'], aggfunc=np.sum)
>>> table
C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

We can also fill missing values using the `fill_value` parameter.

>>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
...                     columns=['C'], aggfunc=np.sum, fill_value=0)
>>> table
C        large  small
A   B
bar one      4      5
    two      7      6
foo one      4      1
    two      0      6

The next example aggregates by taking the mean across multiple columns.

>>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
...                     aggfunc={'D': np.mean,
...                              'E': np.mean})
>>> table
                D         E
A   C
bar large  5.500000  7.500000
    small  5.500000  8.500000
foo large  2.000000  4.500000
    small  2.333333  4.333333

We can also calculate multiple types of aggregations for any given
value column.

>>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
...                     aggfunc={'D': np.mean,
...                              'E': [min, max, np.mean]})
>>> table
                  D   E
               mean max      mean  min
A   C
bar large  5.500000   9  7.500000    6
    small  5.500000   9  8.500000    8
foo large  2.000000   5  4.500000    4
    small  2.333333   6  4.333333    2
File:      d:\python\pythonpivottable\.pivottable\lib\site-packages\pandas\core\reshape\pivot.py
Type:      function

In [50]:
from itertools import count
from operator import countOf


pd.pivot_table(sample, index=['CPU'], columns=['Status'], values=['Asset Tag'], aggfunc= np.count_nonzero, fill_value= 0, margins= True, margins_name="Total")

                                            Asset Tag                 \
Status                  Awaiting Re-Imaging (pending) CSR (archived)
CPU
Apple M1                                            0              0
Apple M2                                            0              0
Intel Core 2 Duo                                    0              0
Intel Core i3                                       0             23
Intel Core i5                                       3             12
Intel Core i7                                       0              1
Intel Pentium Dual-Core                             0              0
Intel Xeon                                          0              0
Total                                               3             36

                                                                        \
Status                  CSR (deployed) New (deployable) OGF (archived)
CPU
Apple M1                             0                0              0
Apple M2                             0                1              0
Intel Core 2 Duo                     0                0              0
Intel Core i3                        2                0              1
Intel Core i5                        0               14              7
Intel Core i7                        0                1              0
Intel Pentium Dual-Core              0                0              0
Intel Xeon                           0                0              0
Total                                2               16              8

                                                                       \
Status                  Production (deployable) Production (deployed)
CPU
Apple M1                                      0                     3
Apple M2                                      0                     0
Intel Core 2 Duo                              0                     0
Intel Core i3                                 0                    25
Intel Core i5                                 2                   446
Intel Core i7                                 0                    19
Intel Pentium Dual-Core                       0                     1
Intel Xeon                                    0                     2
Total                                         2                   496

                                                       \
Status                  Production Stock (deployable)
CPU
Apple M1                                            0
Apple M2                                            0
Intel Core 2 Duo                                    0
Intel Core i3                                       0
Intel Core i5                                      31
Intel Core i7                                       0
Intel Pentium Dual-Core                             0
Intel Xeon                                          0
Total                                              31

                                                                      \
Status                  Production Stock (deployed) Scrap (archived)
CPU
Apple M1                                          0                0
Apple M2                                          0                0
Intel Core 2 Duo                                  0                1
Intel Core i3                                     0               25
Intel Core i5                                     1               30
Intel Core i7                                     0                0
Intel Pentium Dual-Core                           0                0
Intel Xeon                                        0                0
Total                                             1               56

                                                          \
Status                  Scrap (deployed) Spare (pending)
CPU
Apple M1                               0               0
Apple M2                               0               0
Intel Core 2 Duo                       0               0
Intel Core i3                          1               2
Intel Core i5                          1              11
Intel Core i7                          0               1
Intel Pentium Dual-Core                0               0
Intel Xeon                             0               0
Total                                  2              14

                                                   \
Status                  To be Scrapped (deployed)
CPU
Apple M1                                        0
Apple M2                                        0
Intel Core 2 Duo                                0
Intel Core i3                                   1
Intel Core i5                                   1
Intel Core i7                                   0
Intel Pentium Dual-Core                         0
Intel Xeon                                      0
Total                                           2

                                                       \
Status                  To be Scrapped (undeployable)
CPU
Apple M1                                            0
Apple M2                                            0
Intel Core 2 Duo                                    0
Intel Core i3                                      76
Intel Core i5                                      27
Intel Core i7                                       1
Intel Pentium Dual-Core                             0
Intel Xeon                                          0
Total                                             104


Status                  Under Service (undeployable) Total
CPU
Apple M1                                           0     3
Apple M2                                           0     1
Intel Core 2 Duo                                   0     1
Intel Core i3                                      0   156
Intel Core i5                                      3   589
Intel Core i7                                      2    25
Intel Pentium Dual-Core                            0     1
Intel Xeon                                         0     2
Total                                              5   778

In [51]:
table=pd.pivot_table(sample, index=['CPU'], columns=['Status'], values=['Asset Tag'], aggfunc= np.count_nonzero, fill_value= 0, margins= True, margins_name="Total")

In [52]:
type(table)

pandas.core.frame.DataFrame

In [60]:
table.query('CPU== ["Intel Core i3", "Intel Core i5", "Intel Core i7", "Total"]')

                                  Asset Tag                                \
Status        Awaiting Re-Imaging (pending) CSR (archived) CSR (deployed)
CPU
Intel Core i3                             0             23              2
Intel Core i5                             3             12              0
Intel Core i7                             0              1              0
Total                                     3             36              2

                                                                       \
Status        New (deployable) OGF (archived) Production (deployable)
CPU
Intel Core i3                0              1                       0
Intel Core i5               14              7                       2
Intel Core i7                1              0                       0
Total                       16              8                       2

                                                                   \
Status        Production (deployed) Production Stock (deployable)
CPU
Intel Core i3                    25                             0
Intel Core i5                   446                            31
Intel Core i7                    19                             0
Total                           496                            31

                                                                             \
Status        Production Stock (deployed) Scrap (archived) Scrap (deployed)
CPU
Intel Core i3                           0               25                1
Intel Core i5                           1               30                1
Intel Core i7                           0                0                0
Total                                   1               56                2

                                                         \
Status        Spare (pending) To be Scrapped (deployed)
CPU
Intel Core i3               2                         1
Intel Core i5              11                         1
Intel Core i7               1                         0
Total                      14                         2


Status        To be Scrapped (undeployable) Under Service (undeployable) Total
CPU
Intel Core i3                            76                            0   156
Intel Core i5                            27                            3   589
Intel Core i7                             1                            2    25
Total                                   104                            5   778